Repository CeyLabs/BitcoinDeepaBot-TMA, pull requests merged in 2025-08, with the labels that each got.

#27 feat: enhance subscription form validation and UI feedback
  src/app/dashboard/subscription/page.tsx
  src/app/subscription/page.tsx
Labels: Review effort 2/5

#40 feat: Implement `Didit` integration
  src/app/api/user/kyc/initiate/route.ts
  src/app/api/user/kyc/status/route.ts
  src/app/dashboard/page.tsx
  src/app/verification/page.tsx
Labels: enhancement, Review effort 4/5, Possible security concern

#37 feat: Remove background color and use native telegram color
  src/app/layout.tsx
  src/app/onboard/page.tsx
  src/app/payment/cancel/page.tsx
  src/app/payment/success/page.tsx
  src/app/subscription/page.tsx
  src/components/LoadingPage.tsx
  src/styles/theme.css
Labels: Review effort 2/5

#36 feat: integrate tanstack query for cached data
  package-lock.json
  package.json
  src/app/context/providers.tsx
  src/app/context/transition.tsx
  src/app/dashboard/history/page.tsx
  src/app/dashboard/loading.tsx
  src/app/dashboard/page.tsx
  src/app/dashboard/subscription/page.tsx
  src/app/subscription/page.tsx
  src/components/bottomNavigation.tsx
  src/components/skeletons/BalanceCardSkeleton.tsx
  src/components/skeletons/ChartSkeleton.tsx
  src/components/skeletons/ListItemSkeleton.tsx
  src/lib/query-keys.ts
Labels: Review effort 3/5

#52 Rename Plans nav item to Membership
  src/components/bottomNavigation.tsx
Labels: codex, Review effort 1/5

#50 Rename DCA charts to RewardsChart and update messaging
  src/app/dashboard/page.tsx
  src/components/DCAChart.tsx
  src/components/RewardsChart.tsx
Labels: Review effort 2/5, codex

#49 Update reward wording on success page
  src/app/payment/success/page.tsx
Labels: codex, Review effort 1/5

#48 docs: emphasize membership rewards over DCA
  CLAUDE.md
Labels: codex, Review effort 1/5

#43 feat(subscription): revamp tab toggle UI and add haptic feedback
  src/app/dashboard/subscription/page.tsx
Labels: enhancement, Review effort 2/5
